.TH "IXP_RESPOND" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_respond
.SH SYNOPSIS

.nf
#include <ixp.h>

void ixp_respond(Ixp9Req *req, const char *error);
.fi


.SH DESCRIPTION
.P
Sends a response to the given request. The response is
constructed from the \fIofcall\fR member of the \fIreq\fR parameter, or
from the \fIerror\fR parameter if it is non\-null. In the latter
case, the response is of type RError, while in any other case it
is of the same type as \fIreq\fR\->\fIofcall\fR, which must match the
request type in \fIreq\fR\->\fIifcall\fR.
.SH SEE ALSO
.P
Ixp9Req(3), ixp_printfcall(3)

