.TH "IXP_WRITE" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_write, ixp_pwrite
.SH SYNOPSIS

.nf
#include <ixp.h>

long ixp_write(IxpCFid *fid, const void *buf, long count);

long ixp_pwrite(IxpCFid *fid, const void *buf, long count, int64_t offset);
.fi


.SH PARAMETERS

.TP
buf
A buffer holding the contents to store.
.TP
count
The number of bytes to store.
.TP
offset
The offset at which to write the data.

.SH DESCRIPTION
.P
ixp_write and ixp_pwrite each write \fIcount\fR bytes of
data stored in \fIbuf\fR to the file pointed to by C<fid>.
ixp_write writes its data at its stored offset, and
increments it by \fIcount\fR. ixp_pwrite writes its data a
\fIoffset\fR and does not alter C<fid>'s stored offset.
.SH RETURN VALUE
.P
These functions return the number of bytes actually
written. Any value less than \fIcount\fR must be considered
a failure.
.SH SEE ALSO
.P
ixp_mount(3), ixp_open(3), ixp_read(3)

