.TH "IXP_PRINT" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_print, ixp_vprint, ixp_vsmprint
.SH SYNOPSIS

.nf
#include <ixp.h>

int ixp_print(IxpCFid *fid, const char *fmt, ...);

int ixp_vprint(IxpCFid *fid, const char *fmt, va_list args);

char*    (*ixp_vsmprint)(const char *fmt, va_list);
.fi


.SH PARAMETERS

.TP
fid
An open IxpCFid to which to write the result.
.TP
fmt
The string with which to format the data.
.TP
args
A va_list holding the arguments to the format
string.
.TP
.RB ...
The arguments to the format string.

.SH DESCRIPTION
.P
These functions act like the standard formatted IO
functions. They write the result of the formatting to the
file pointed to by C<fid>.
.P
\fBixp_vsmprint(3)\fR may be set to a function which will
format its arguments and return a nul\-terminated string
allocated by malloc(3). The default formats its arguments as
printf(3).
.SH RETURN VALUE
.P
These functions return the number of bytes written.
There is currently no way to detect failure.
.SH SEE ALSO
.P
ixp_mount(3), ixp_open(3), printf(3)

