.TH "IXP_PFCALL" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_pfcall, ixp_pqid, ixp_pqids, ixp_pstat, ixp_sizeof_stat
.SH SYNOPSIS

.nf
#include <ixp.h>

void ixp_pfcall(IxpMsg *msg, IxpFcall *fcall);

void ixp_pqid(IxpMsg *msg, IxpQid *qid);

void ixp_pqids(IxpMsg *msg, uint16_t *num, IxpQid qid\fI[]\fR, uint max);

void ixp_pstat(IxpMsg *msg, IxpStat *stat);

uint16_t ixp_sizeof_stat(IxpStat *stat, uint version);
.fi


.SH DESCRIPTION
.P
These convenience functions pack or unpack the contents of
libixp structures into their wire format. They behave as if
\fBixp_pu8(3)\fR, \fBixp_pu16(3)\fR, \fBixp_pu32(3)\fR, \fBixp_pu64(3)\fR, and
\fBixp_pstring(3)\fR were called for each member of the structure
in question. ixp_pqid is to ixp_pqid as \fBixp_pstrings(3)\fR is to
ixp_pstring.
.P
ixp_sizeof_stat returns the size of the packed represention
of \fIstat\fR.
.SH SEE ALSO
.P
IxpMsg(3), ixp_pu8(3), ixp_pu16(3), ixp_pu32(3),
ixp_pu64(3), ixp_pstring(3), ixp_pstrings(3)

