.TH "IXP_SRV_WRITECTL" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_srv_writectl
.SH SYNOPSIS

.nf
#include <ixp_srvutil.h>

char *ixp_srv_writectl(Ixp9Req *req, char *(*fn)(void *, IxpMsg *));
.fi


.SH DESCRIPTION
.P
This utility function is meant to simplify the writing of
pseudo files to which single\-lined commands are written.
In order to use this function, the \fIaux\fR member of
\fIreq\fR\->fid must be nul or an \fBIxpFileId(3)\fR.  Each line of the
written data is stripped of its trailing newline,
nul\-terminated, and stored in an \fBIxpMsg(3)\fR. For each line
thus prepared, \fIfn\fR is called with the IxpMsg pointer and
the the \fIp\fR member of the IxpFileId.

