.TH "IXP_REMOVE" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_remove
.SH SYNOPSIS

.nf
#include <ixp.h>

int ixp_remove(IxpClient *c, const char *path);
.fi


.SH PARAMETERS

.TP
path
The path of the file to remove.

.SH DESCRIPTION
.P
Removes a file or directory from the remote server.
.SH RETURN VALUE
.P
ixp_remove returns 0 on failure, 1 on success.
.SH SEE ALSO
.P
ixp_mount(3)

