.TH "IXP_SRV_FREEFILE" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_srv_freefile
.SH SYNOPSIS

.nf
#include <ixp_srvutil.h>

void ixp_srv_freefile(IxpFileId *fileid);
.fi


.SH DESCRIPTION
.P
Decrease the reference count of the given IxpFileId,
and push it onto the free list when it reaches 0;
.SH SEE ALSO
.P
ixp_srv_getfile(3)

