.TH "IXP_SRV_GETFILE" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_srv_getfile, IxpFileId
.SH SYNOPSIS

.nf
#include <ixp_srvutil.h>

IxpFileId *ixp_srv_getfile(void);

typedef struct IxpFileId        IxpFileId;
struct IxpFileId {
        IxpFileId*      next;
        IxpFileIdU      p;
        bool            pending;
        uint            id;
        uint            index;
        IxpDirtab       tab;
        uint            nref;
        char            volatil;
}
.fi


.SH DESCRIPTION
.P
Obtain an empty, reference counted IxpFileId struct.
.SH SEE ALSO
.P
ixp_srv_clonefiles(3), ixp_srv_freefile(3)

