.TH "IXP_TASKINIT" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_taskinit
.SH SYNOPSIS

.nf
#include <ixp.h>

ixp_taskinit
.fi


.SH DESCRIPTION
.P
This function initializes libixp for use in multithreaded
programs using the libtask threading system. When using libixp in
such programs, this function must be called before any other
libixp functions.
.P
This function is part of libixp_task, which is part of the libixp
distribution, but is not built by default unless enabled in
config.mk.

