.TH "IXP_FREESTAT" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_freestat, ixp_freefcall
.SH SYNOPSIS

.nf
#include <ixp.h>

void ixp_freestat(IxpStat *s);

void ixp_freefcall(IxpFcall *fcall);
.fi


.SH DESCRIPTION
.P
These functions free malloc(3) allocated data in the members
of the passed structures and set those members to nil. They
do not free the structures themselves.
.SH SEE ALSO
.P
IxpFcall(3), IxpStat(3)

