.TH "IXP_SMPRINT" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_smprint
.SH SYNOPSIS

.nf
#include <ixp.h>

char *ixp_smprint(const char *fmt, ...);
.fi


.SH DESCRIPTION
.P
This function formats its arguments as \fBprintf(3)\fR and returns
a \fBmalloc(3)\fR allocated string containing the result.

