.TH "IXP_RUBYINIT" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_rubyinit
.SH SYNOPSIS

.nf
#include <ixp.h>

ixp_rubyinit
.fi


.SH DESCRIPTION
.P
This function initializes libixp for use in multithreaded
programs embedded in the ruby interpreter. When using a pthread
edition of ruby, ixp_pthread_init should be used instead. When
using libixp in such programs, this function must be called
before any other libixp functions.
.P
This function is part of libixp_rubythread, which is part of the
libixp distribution, but is not built by default unless enabled
in config.mk.

