.TH "IXP_NAMESPACE" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_namespace
.SH SYNOPSIS

.nf
#include <ixp.h>

char *ixp_namespace(void);
.fi


.SH DESCRIPTION
.P
Returns the path of the canonical 9p namespace directory.
Either the value of \fB$NAMESPACE\fR, if it's set, or, roughly,
/tmp/ns.\fB${USER\fR\fB}\fR.\fB${DISPLAY\fR:%.0=%\fB}\fR. In the latter case, the
directory is created if it doesn't exist, and it is
ensured to be owned by the current user, with no group or
other permissions.
.SH RETURN VALUE
.P
A statically allocated string which must not be freed
or altered by the caller. The same value is returned
upon successive calls.
.SH BUGS
.P
This function is not thread safe until after its first
call.

