.TH "IXP_MOUNT" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_mount, ixp_mountfd, ixp_nsmount, IxpClient
.SH SYNOPSIS

.nf
#include <ixp.h>

IxpClient *ixp_mount(const char *address);

IxpClient *ixp_mountfd(int fd);

IxpClient *ixp_nsmount(const char *name);

typedef struct IxpClient IxpClient;
struct IxpClient {
        int     fd;
        uint    msize;
        uint    lastfid;
        uint    version;

        /* Private members */
        ...
}
.fi


.SH PARAMETERS

.TP
fd
A file descriptor which is already connected
to a 9P server.
.TP
address
An address (in Plan 9 resource fomat) at
which to connect to a 9P server.
.TP
name
The name of a socket in the process's canonical
namespace directory.

.SH DESCRIPTION
.P
Initiate a 9P connection with the server at \fIaddress\fR,
connected to on \fIfd\fR, or under the process's namespace
directory as \fIname\fR.
.SH RETURN VALUE
.P
A pointer to a new 9P client.
.SH SEE ALSO
.P
ixp_open(3), ixp_create(3), ixp_remove(3), ixp_unmount(3)

