.TH "IXP_PRINTFCALL" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_printfcall
.SH SYNOPSIS

.nf
#include <ixp.h>

void     (*ixp_printfcall)(IxpFcall*);
.fi


.SH DESCRIPTION
.P
When set to a non\-null value, ixp_printfcall is called once for
every incoming and outgoing Fcall. It is intended to simplify the
writing of debugging code for clients, but may be used for any
arbitrary purpose.
.SH SEE ALSO
.P
ixp_respond(3), ixp_serve9conn(3)

