.TH "IXP_DIAL" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_dial, ixp_announce
.SH SYNOPSIS

.nf
#include <ixp.h>

int ixp_dial(const char *address);

int ixp_announce(const char *address);
.fi


.SH PARAMETERS

.TP
address
An address on which to connect or listen,
specified in the Plan 9 resources
specification format
(<protocol>!address\fI[!<port>]\fR)

.SH DESCRIPTION
.P
These functions hide some of the ugliness of Berkely
Sockets. ixp_dial connects to the resource at \fIaddress\fR,
while ixp_announce begins listening on \fIaddress\fR.
.SH RETURN VALUE
.P
These functions return file descriptors on success, and \-1
on failure. ixp_errbuf(3) may be inspected on failure.
.SH SEE ALSO
.P
socket(2)

