.TH "IXP_PDATA" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_pdata
.SH SYNOPSIS

.nf
#include <ixp.h>

void ixp_pdata(IxpMsg *msg, char **data, uint len);
.fi


.SH DESCRIPTION
.P
Packs or unpacks a raw character buffer of size \fIlen\fR.
.P
If \fImsg\fR\->mode is MsgPack, buffer pointed to by \fIdata\fR is
packed into the buffer at \fImsg\fR\->pos. If \fImsg\fR\->mode is
MsgUnpack, the address pointed to by \fIs\fR is loaded with a
malloc(3) allocated buffer with the contents of the buffer at
\fImsg\fR\->pos.  In either case, \fImsg\fR\->pos is advanced by the
number of bytes read or written. If the action would advance
\fImsg\fR\->pos beyond \fImsg\fR\->end, \fImsg\fR\->pos is still advanced
but no other action is taken.
.SH SEE ALSO
.P
IxpMsg(3), ixp_pstring(3)

