.TH "IXP_SRV_DATA2CSTRING" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_srv_data2cstring
.SH SYNOPSIS

.nf
#include <ixp_srvutil.h>

void ixp_srv_data2cstring(Ixp9Req *req);
.fi


.SH DESCRIPTION
.P
Ensure that the data member of \fIreq\fR is null terminated,
removing any new line from its end.
.SH SEE ALSO
.P
Ixp9Req(3)

