.TH "IXP_PU8" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_pu8, ixp_pu16, ixp_pu32, ixp_pu64
.SH SYNOPSIS

.nf
#include <ixp.h>

void ixp_pu8(IxpMsg *msg, uint8_t *val);

void ixp_pu16(IxpMsg *msg, uint16_t *val);

void ixp_pu32(IxpMsg *msg, uint32_t *val);

void ixp_pu64(IxpMsg *msg, uint64_t *val);
.fi


.SH DESCRIPTION
.P
These functions pack or unpack an unsigned integer of the
specified size.
.P
If \fImsg\fR\->mode is MsgPack, the value pointed to by \fIval\fR is
packed into the buffer at \fImsg\fR\->pos. If \fImsg\fR\->mode is
MsgUnpack, the packed value at \fImsg\fR\->pos is loaded into the
location pointed to by \fIval\fR. In both cases, \fImsg\fR\->pos is
advanced by the number of bytes read or written. If the call
would advance \fImsg\fR\->pos beyond \fImsg\fR\->end, \fImsg\fR\->pos is
advanced, but nothing is modified.
.SH SEE ALSO
.P
IxpMsg(3)

