.TH "IXP_SRV_CLONEFILES" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_srv_clonefiles
.SH SYNOPSIS

.nf
#include <ixp_srvutil.h>

IxpFileId *ixp_srv_clonefiles(IxpFileId *fileid);
.fi


.SH DESCRIPTION
.P
Increase the reference count of every IxpFileId linked
to \fIfileid\fR.
.SH SEE ALSO
.P
ixp_srv_getfile(3)

