.TH "IXP_UNSETTIMER" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_unsettimer
.SH SYNOPSIS

.nf
#include <ixp.h>

int ixp_unsettimer(IxpServer *srv, long id);
.fi


.SH PARAMETERS

.TP
id
The id number of the timer to void.

.SH DESCRIPTION
.P
Voids the timer identified by \fIid\fR.
.SH RETURN VALUE
.P
Returns true if a timer was stopped, false
otherwise.
.SH SEE ALSO
.P
ixp_settimer(3), ixp_serverloop(3)

