.TH "IXP_READ" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_read, ixp_pread
.SH SYNOPSIS

.nf
#include <ixp.h>

long ixp_read(IxpCFid *fid, void *buf, long count);

long ixp_pread(IxpCFid *fid, void *buf, long count, int64_t offset);
.fi


.SH PARAMETERS

.TP
buf
A buffer in which to store the read data.
.TP
count
The number of bytes to read.
.TP
offset
The offset at which to begin reading.

.SH DESCRIPTION
.P
ixp_read and ixp_pread each read \fIcount\fR bytes of data
from the file pointed to by \fIfid\fR, into \fIbuf\fR. ixp_read
begins reading at its stored offset, and increments it by
the number of bytes read. ixp_pread reads beginning at
\fIoffset\fR and does not alter \fIfid\fR's stored offset.
.SH RETURN VALUE
.P
These functions return the number of bytes read on
success and \-1 on failure.
.SH SEE ALSO
.P
ixp_mount(3), ixp_open(3), ixp_write(3)

