.TH "IXP_FCALL2MSG" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_fcall2msg, ixp_msg2fcall
.SH SYNOPSIS

.nf
#include <ixp.h>

uint ixp_fcall2msg(IxpMsg *msg, IxpFcall *fcall);

uint ixp_msg2fcall(IxpMsg *msg, IxpFcall *fcall);
.fi


.SH DESCRIPTION
.P
These functions pack or unpack a 9P protocol message. The
message is set to the appropriate mode and its position is
set to the begining of its buffer.
.SH RETURN VALUE
.P
These functions return the size of the message on
success and 0 on failure.
.SH SEE ALSO
.P
IxpMsg(3), ixp_pfcall(3)

