.TH "IXP_SETTIMER" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_settimer
.SH SYNOPSIS

.nf
#include <ixp.h>

long ixp_settimer(IxpServer *srv, long msec, void (*fn)(long, void *), void *aux);
.fi


.SH PARAMETERS

.TP
msec
The timeout in milliseconds.
.TP
fn
The function to call after \fImsec\fR milliseconds
have elapsed.
.TP
aux
An arbitrary argument to pass to \fIfn\fR when it
is called.

.SH DESCRIPTION
.P
Initializes a callback\-based timer to be triggerred after
\fImsec\fR milliseconds. The timer is passed its id number
and the value of \fIaux\fR.
.SH RETURN VALUE
.P
Returns the new timer's unique id number.
.SH SEE ALSO
.P
ixp_unsettimer(3), ixp_serverloop(3)

