.TH "IXP_HANGUP" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_hangup, ixp_server_close
.SH SYNOPSIS

.nf
#include <ixp.h>

void ixp_hangup(IxpConn *c);

void ixp_server_close(IxpServer *s);
.fi


.SH DESCRIPTION
.P
ixp_hangup closes a connection, and stops the server
listening on it. It calls the connection's close
function, if it exists. ixp_server_close calls ixp_hangup
on all of the connections on which the server is
listening.
.SH SEE ALSO
.P
ixp_listen(3), IxpServer(3), IxpConn(3)

