.TH "IXP_CLOSE" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
ixp_close
.SH SYNOPSIS

.nf
#include <ixp.h>

int ixp_close(IxpCFid *f);
.fi


.SH DESCRIPTION
.P
Closes the file pointed to by \fIf\fR and frees its
associated data structures;
.SH RETURN VALUE
.P
Returns 1 on success, and zero on failure.
.SH SEE ALSO
.P
ixp_mount(3), ixp_open(3)

