.TH "IXPFID" 3 "2025 Dec" "libixp Manual"

.SH NAME
.P
IxpFid
.SH SYNOPSIS

.nf
#include <ixp.h>

typedef struct IxpFid IxpFid;
struct IxpFid {
        char*           uid;    /* The uid of the file opener. */
        void*           aux;    /* Arbitrary pointer, to be used by handlers. */
        uint32_t                fid;    /* The ID number of the fid. */
        IxpQid          qid;    /* The filesystem-unique QID of the file. */
        signed char     omode;  /* The open mode of the file. */
        uint            iounit; /* The maximum size of any IO request. */

        /* Private members */
        ...
}
.fi


.SH DESCRIPTION
.P
Represents an open file for a 9P connection. The same
structure persists as long as the file remains open, and is
installed in the \fBIxp9Req(3)\fR structure for any request Fcall
which references it. Handlers may use the \fIaux\fR member to
store any data which must persist for the life of the open
file.
.SH SEE ALSO
.P
Ixp9Req(3), IxpQid(3), IxpOMode(3)

