ROOT= ..
include ${ROOT}/mk/hdr.mk
include ${ROOT}/mk/ixp.mk

TARG =	libixp

OBJ =	client    \
	convert   \
	error     \
	intmap    \
	message   \
	request   \
	rpc       \
	server    \
	socket    \
	thread    \
	transport \
	util

include ${ROOT}/mk/lib.mk

