ROOT= ..
include $(ROOT)/mk/hdr.mk
include $(ROOT)/mk/ixp.mk

TARG =	libixp

OBJ =	client    \
	convert   \
	error     \
	intmap    \
	message   \
	request   \
	rpc       \
	server    \
	srv_util  \
	socket    \
	thread    \
	timer     \
	transport \
	util

include ${ROOT}/mk/lib.mk

